### ISSUE TITLE
Pass QuorumSpec via WithQuorumSpec

### ISSUE THREAD

**Issue by meling** [relab/gorums#121]
I have an idea to get rid of the `QuorumSpec` as a separate argument to:
```go
func (m *Manager) NewConfiguration(qspec QuorumSpec, opts ...gorums.ConfigOption) (c *Configuration, err error) {
```
Instead we can do:
```go
func (m *Manager) NewConfiguration(opts ...gorums.ConfigOption) (c *Configuration, err error) {
```
And pass the `qspec` instance via `WithQuorumSpec(qspec)`.

This `WithQuorumSpec()` must accept an `interface{}`, but we can just do a `qspec.(QuorumSpec)` before storing it in the `dev.Configuration` struct. I like this approach because not all configurations need a `QuorumSpec`, and it makes the API a bit cleaner.

There is only a small snag, in that the `gorums.NewConfiguration` has no concept of `QuorumSpec`, and it would be a mistake to add it since `QuorumSpec` is a generated interface specific to quorum calls defined in the application's proto file.

I've considered two approaches to work around this snag.
1. Let `gorums.NewConfiguration` receive and process `WithQuorumSpec` and just return it as an `interface{}`, as a separate return value.
2. Make a new function `gorums.GetQSpec()` that also processes `ConfigOption` types, but only returns the `qspec`. See code below.

I don't really like alternative 1 above because it makes things more coupled than they should.

What do you think about alternative 2? Are there any other alternatives?

```go
func GetQSpec(opts ...ConfigOption) interface{} {
	o := newConfigOptions()
	for _, opt := range opts {
		opt(&o)
	}
	return o.qspec
}
```
Using it from `dev.NewConfiguration` would look something like this:
```go
	if qspec, ok := gorums.GetQSpec(opts...).(QuorumSpec); !ok {
		return nil, errors.New("QuorumSpec error")
	} else {
		c.qspec = qspec
	}
	return c, nil
```

PS: This is probably referring to code as it looks in PR #120.

**Comment by Raytar** [comment]
One problem with passing `QuorumSpec` as an `interface{}` is that we won't get any compiler errors if the `qspec` object doesn't implement the `QuorumSpec` interface.

If the main idea is to get rid of the `qspec` argument in `NewConfiguration` when there are no quorum functions, then we could instead use templates to omit the `qspec` argument when it is not needed. That way we keep the compile-time type checking.

**Comment by meling** [comment]
I prefer not to generate a separate `NewConfiguration` method with a different signature for methods that don't use the `QuorumSpec`.

PR #122 implements a non-type safe approach. A draft generics idea is sketched [here](https://go2goplay.golang.org/p/I-p3GE0XhKm). However, we could do better with generics, e.g., I think we can do a single `With[Type]()` method.
