### ISSUE TITLE
Having untracked generated code in the tests causes problems with go modules

### ISSUE THREAD

**Issue by Raytar** [relab/gorums#127]
Running `go mod tidy` in hotstuff results in go complaining that it can't find the `dummy` test package.
This is probably because we currently `.gitignore` the generated code from the tests.
This is easily solved by including the generated code for the `dummy` package, but we should probably reconsider whether we should continue ignoring the generated tests.

```text
❯ go mod tidy   
go: finding module for package github.com/relab/gorums/tests/dummy
github.com/relab/hotstuff imports
        github.com/relab/gorums tested by
        github.com/relab/gorums.test imports
        github.com/relab/gorums/tests/dummy: module github.com/relab/gorums@latest found (v0.3.0), but does not contain package github.com/relab/gorums/tests/dummy
```

**Comment by meling** [comment]
Does it make sense to include anything from `tests` in the releases? The tests are only used when developing Gorums, and for learning. But learning can be done outside of the released module itself.
