### ISSUE TITLE
Prevent codegen errors when protoc-gen-gorums version differs from imported gorums version

### ISSUE THREAD

**Issue by Raytar** [relab/gorums#128]
If the version of `protoc-gen-gorums` differs from the gorums version imported by a module, we may encounter problems with code generation. See: https://github.com/relab/hotstuff/issues/28

Can we detect this in the code generator and output warnings/errors?

**Comment by meling** [comment]
We currently need to update the `protoc-gen-gorums` version [manually](https://github.com/relab/gorums/blob/master/cmd/protoc-gen-gorums/gengorums/version.go#L20). However, I've seen some interesting approaches to set the version based on tags. Will look into that.
