### ISSUE TITLE
protoc-gen-gorums: generates useless Equal and VerboseEqual functions

### ISSUE THREAD

**Issue by meling** [relab/gorums#13]
The plugin generates Go code for different `Equal` and `VerboseEqual` functions that are not used currently. These reduce test coverage for @wruiwr's stuff. Suggest that we remove those if they are not needed for something that I didn't see (@tormoder); it is a two line fix and the tests pass without these functions. 

The fix is simply to comment or remove [https://github.com/relab/gorums/blob/master/cmd/protoc-gen-gorums/main.go#L26](url) and [https://github.com/relab/gorums/blob/master/cmd/protoc-gen-gorums/main.go#L29](url)

**Comment by tormoder** [comment]
Yes, the two methods are enabled by default in the binary.

They are meant to be used for example in tests as you do here:
https://github.com/relab/gorums/blob/master/byzq/authdataspec_test.go#L248

We stop enabling them in the binary, and let users enable them if needed using gogoprotobuf options in their proto-files, e.g.: 

`option (gogoproto.verbose_equal_all) = true;`

(See for example https://godoc.org/github.com/gogo/protobuf/plugin/equal).
