### ISSUE TITLE
QSpec objects versus passing quorum functions as arguments

### ISSUE THREAD

**Issue by Raytar** [relab/gorums#157]
I am opening this issue to gather some thoughts on whether quorum specification (qspec) objects have any benefits compared to simply passing the quorum function as an argument to each quorum call.

Currently, a quorum function must be implemented by a qspec object.
Qspec objects are stored in configurations:

```go
type qspec struct {}

func (qspec) WriteQF(in *proto.WriteRequest, replies map[uint32]*proto.WriteResponse) (*proto.WriteResponse, bool) {
    ...
}

// Currenlty, the quorum function is made available to quorum call through the qspec object
cfg, _ := mgr.NewConfiguration(qspec{}, ...)
cfg.Write(...)
```

Alternatively, we could pass the quorum functions to the quorum calls as arguments:

```go
// We could instead pass it to the quorum call directly
cfg.Write(..., func(in *proto.WriteRequest, replies map[uint32]*proto.WriteResponse) (*proto.WriteResponse, bool) {
    ...
})

// This also works without closures,
// and the state of the qspec object can be modified
// if a pointer receiver is used for the QF.
cfg.Write(..., qspec{}.WriteQF)
```

My thoughts:

* I think that I prefer the "ergonomics" of using a qspec object because implementing the qspec is analogous to implementing the server-side handlers.
* Passing quorum functions as arguments makes it easy to give different quorum functions for subsequent quorum calls.
    - Though I am not sure when this could be useful.

**Comment by meling** [comment]
I guess the question is whether or not a qspec belongs together with the configuration object. You could argue that the function argument approach can still be decoupled from the quorum call execution path by defining it outside the code path and just pass it as an argument; e.g., we could have a library of standard quorum functions that you pass in. But in this case, you cannot leverage the locally defined variables inside the quorum function.

**Comment by leandernikolaus** [comment]
I always thought of a quorum function and qspec as belonging to the configuration, rather than to a specific call.
Thus, I find it reasonable, if you want to use different qspecs, to rather use different configurations than passing different 

I am unsure whether this is actually possible in the current gorums.

The disadvantage with qspecs, is that someone may actually modify state in these objects, which could be problematic and not thread safe.

**Comment by meling** [comment]
I'm closing this since there is no clear use case for the function closure approach. Should a use case arise, we can revisit the topic.
