### ISSUE TITLE
bug: race condition when accessing configuration from separate goroutines

### ISSUE THREAD

**Issue by vidarandrebo** [relab/gorums#183]
Race condition can be replicated by running `TestConfigConcurrentAccess` in [`config_test.go`](https://github.com/relab/gorums/blob/config-race-condition/config_test.go) (run with `-race` flag).

In the generated code, the node-slice is not assigned until the first call to `Nodes()`.

```golang
// Nodes returns a slice of each available node. IDs are returned in the same
// order as they were provided in the creation of the Manager.
//
// NOTE: mutating the returned slice is not supported.
func (c *Configuration) Nodes() []*Node {
	if c.nodes == nil {
		c.nodes = make([]*Node, 0, c.Size())
		for _, n := range c.RawConfiguration {
			c.nodes = append(c.nodes, &Node{n})
		}
	}
	return c.nodes
}
```

`c.nodes` should instead be assigned when config object is created.

**Comment by meling** [comment]
This is a reasonable request. Feel free to file a PR.

**Comment by vidarandrebo** [comment]
Ok, I will look into it.
