### ISSUE TITLE
Should we remove the plain correctable version?

### ISSUE THREAD

**Issue by meling** [relab/gorums#19]
There are two different correctable implementations as of now, but they are very similar in some some aspects, except that the prelim one uses streams, and can be updated multiple times from the same server (if I understand correctly). Below is a diff of the real code changes; all other changes are comments and imports. 

I guess the question I'm asking is if it is worth maintaining two implementations that are almost the same; I believe @tormoder raised the question himself in a discussion a while ago. If we decide to remove the plain correctable version in favor of the streaming version, it would be easier to maintain one version and also get the documentation right. Since we aren't using any of the two in any prototypes, except for the test cases, I guess the main issue to consider is if we can imagine a use case where one or both may be useful. I think we have discussed EPaxos as a potential target for a correctable implementation.

If we can solve the issue of request-reply matching raised by @tormoder on slack, we could possibly achieve the two different functionalities with the same correctable implementation.

```go
132c130
< 		replyValues = make([]*{{.FQRespName}}, 0, c.n)
---
> 		replyValues = make([]*{{.FQRespName}}, 0, c.n*2)
143c141
< 			resp.NodeIDs = append(resp.NodeIDs, r.nid)
---
> 			resp.NodeIDs = appendIfNotPresent(resp.NodeIDs, r.nid)
167c165
< 		if errCount+len(replyValues) == c.n {
---
> 		if errCount == c.n { // Can't rely on reply count.
174c172,190
< {{template "callGRPC" .}}
---
> func callGRPC{{.MethodName}}(ctx context.Context, node *Node, arg *{{.FQReqName}}, replyChan chan<- {{.UnexportedTypeName}}) {
> 	x := New{{.ServName}}Client(node.conn)
> 	y, err := x.{{.MethodName}}(ctx, arg)
> 	if err != nil {
> 		replyChan <- {{.UnexportedTypeName}}{node.id, nil, err}
> 		return
> 	}
>
> 	for {
> 		reply, err := y.Recv()
> 		if err == io.EOF {
> 			return
> 		}
> 		replyChan <- {{.UnexportedTypeName}}{node.id, reply, err}
> 		if err != nil {
> 			return
> 		}
> 	}
> }```

**Comment by tormoder** [comment]
If we are going to remove one, I would consider removing the more complex version, CorrectablePrelim, since we don't have a use case for it.

For EPaxos (and the solution described in #16) I would use a basic Correctable since there is no need for the servers to reply with more than a single reply per call, and using the CorrectablePrelim would just add unnecessary complexity/overhead at the servers by creating reply streams for each call.

**Comment by meling** [comment]
Closing this for now. We can start another issue to discuss removing the complex version later.
