### ISSUE TITLE
Two struct embeddings in Node can simplify API

### ISSUE THREAD

**Issue by meling** [relab/gorums#22]
The following two struct embeddings in `Node` can simplify the use of `Send()`, `CloseAndRecv()` and service methods on the node itself:
```go
-       StorageClient StorageClient
+       StorageClient
```
```
-       WriteAsyncClient Storage_WriteAsyncClient
+       Storage_WriteAsyncClient
```
Some simple examples:
```go
-               rreply, err := node.StorageClient.ReadNoQC(ctx, &qc.ReadRequest{})
+               rreply, err := node.ReadNoQC(ctx, &qc.ReadRequest{})
```
```go
-       _, _ = n.WriteAsyncClient.CloseAndRecv()
+       _, _ = n.CloseAndRecv()
```
Any objections? I've committed the implementation on a separate branch (see commit 65db0c5), because I'm not sure if it is a good idea to keep these fields in the `Node` struct. But haven't thought carefully about it. One challenge is if we want to have more fields for different types of methods.

I was actually looking at how it would work to do client streaming to solve our other problem in #16, and found the need to keep the client side stream along with the node when I was looking at node, seeing there is already something similar there. Though I'm not quite sure where is the best place to store these types of things; in the `Node` or in some alongside data structure that maps from node or its id to these things.

**Comment by tormoder** [comment]
What if you have more than one method that is a client-server stream? How do you call `CloseAndRecv` on each one? 

It works for this case since there is only one multicast method defined for the service.

**Comment by meling** [comment]
@tormoder Yes, I know. But I'm questioning if these fields belong in `Node`. I think it is convenient if they are in `Node`, but software engineering wise I'm not sure. Will take another look.

**Comment by meling** [comment]
Closing and deleted the branch. It is better to keep it as is. I've made some other changes to master though.
