### ISSUE TITLE
Generated code depends on the Gorums package

### ISSUE THREAD

**Issue by tormoder** [relab/gorums#23]
Original issue by @s111 was relab/gorums-dev#11.

**s111 commented on Jan 6**
As far as I can tell, there is no reason for code generated by Gorums to need Gorums as a depenedency.
This was not the case until the introduction of custom options on services: diff

Examples of current generated code:
raft.pb.go
register.pb.go

These contain `import _ "github.com/relab/gorums"` which forces the project to bring along Gorums as a dependency to build, even though it is never used.

The cause seems to be rooted in `import "github.com/relab/gorums/gorums.proto";` in the proto files, causing [generator.go:L1453](https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L1453) to be executed.

The `import _ "github.com/relab/gorums"` line can be removed, and the project works and builds fine without needing Gorums. However it would be better if the generation processes avoided the line altogether, so that anyone starting out with Gorums wouldn't need to learn this trick.
￼
**tormoder commented on Jan 6**
(First thoughts, if have to look at this more carefully.)

The comment in your link says:
```
// We need to import all the dependencies, even if we don't reference them,
// because other code and tools depend on having the full transitive closure
// of protocol buffer types in the binary.
```
And the import does have side-effects via ìnit():
https://github.com/relab/gorums/blob/master/gorums.pb.go#L95
where the gorums extensions are registered in the protobuf "global registry of extensions":
https://github.com/gogo/protobuf/blob/0516412251d96185a7f150ed58e036eb66a40ecd/proto/extensions.go#L669

The same thing will happen (the dot import) also if the standard Google ("well-known") protobuf types are used. (See https://github.com/golang/protobuf/tree/master/ptypes, 'empty', 'timestamp' etc.).
￼
**s111 commented on Jan 6 • edited**
When registering types, the import is actually used in the resulting file.
In this case, we are only registering extensions that are used in the generation phase, and are not actually used in the generated file?
￼
**tormoder commented on Jan 9**
Yes, that's true, since this for service methods, and not actual messages.

I don't currently know how to fix this, or if it worth changing.
The import is done in the main top-level (Go) protobuf generator, before the gRPC and gorums plugins.
I don't want to fork the protobuf library just for this one exception.

I think it is also just importing the `gorums.pb.go` file, which is about ~100 lines of code.

Size test:

Raft server binary with import:
`-rwxr-xr-x 1 tormod users 11989058 Jan 9 11:41 replica`

Raft server binary without import:
`-rwxr-xr-x 1 tormod users 10711447 Jan 9 11:42 replica`

Approx. 1.2 MB diff.

**Comment by meling** [comment]
I've marked this as won't fix, unless there is anything that we can do with this. As I understand the issue, it doesn't have any adverse effects other than compiling to a larger binary. If @s111 believe this issue still has merit, perhaps it should be reported up stream and fixed there. Otherwise, what else can be done about this?

Feel free to close the issue, if we agree that we won't fix it. Otherwise, please remove the won't fix and add comments regarding possible ways to resolve the issue.

**Comment by s111** [comment]
I agree that it would be hard to fix this without a change upstream, so I'm closing this issue.
