### ISSUE TITLE
Add convenience methods to the configuration object

### ISSUE THREAD

**Issue by s111** [relab/gorums#28]
What do you think of this change to the configuration object?

- Add `add/remove/replace` convenience methods to `Configuration`, i.e., c.add(x, q) is identical to `Manager.NewConfiguration(append(c.NodeIDs(), x), q)` and similar for `remove` and `replace`. (I don't know if `replace` is actually useful, I was thinking if we wanna change the IP of a node on the fly, but that can be achieved by just using hostnames and DNS).
  - (We could maybe drop the need for a new quorum spec when using the `add/remove` methods by adding a `OnChange` method to the `QuorumSpec`, i.e., this method would be implemented and would be responsible for changing the read and write quorum size and etc.., when a new configuration is created from an existing configuration with that QuorumSpec)

**Comment by tormoder** [comment]
Initially, when we started on Gorums, I on purpose did not make it possible to
change a configuration after it was created (i.e. a configuration is
immutable).

The reason for for this is that when we built Goxos, we started manipulating
something similar to configurations with operations such as add/remove, and
that led to complex synchronization procedures and problems in our application
when performing reconfigurations. Gorums is somewhat a response to that; you
should explicitly create a new configuration if you want to change the set of
nodes or use different configurations simultaneously etc.

Having said that, I'm still interested in hearing reasons/use cases for having
such methods available.

**Comment by s111** [comment]
Note that I'm not suggesting mutating `c1` when doing `c1.add(n3)`, I'm suggesting that a new configuration `c2` be created with nodes `nodes(c1) + n3` and possibly inheriting the quorum spec.

**Comment by tormoder** [comment]
Aha. Sorry, I misunderstood.

Do you mean something like:
```func (c *Configuration) Add(...node and possibly qspec...) *Configuration```

**Comment by s111** [comment]
Yes, either (easier to implement):
```go
func (c *Configuration) Add(...node, qspec) *Configuration
```
or:
```go
func (c *Configuration) Add(...node) *Configuration
```
where in the last approach the new configurations qspec would be derived from the parent configuration's qspec. I was thinking about using some kind of factory function, i.e., could we have the developer provide a function `func NewQuorumSpec(n int) QuorumSpec`? Or maybe that doesn't fit all use cases?
Quick example:
```go
func (m *Manager) NewConfiguration(...nodes, qsf func(n) QuorumSpec) *Configuration {
...
c.qspec = qsf(len(nodes))
...
return c
}
```
When doing `c1.add(n3)` the new `c2` would have `QuorumSpec` equal to `qsf(len(c1)+1)`.

**Comment by meling** [comment]
The template for a `QuorumSpec` constructor seems to be too limiting for several of our use cases. For example, I have the following three examples:
```go
func NewAuthDataQ(n int, priv *ecdsa.PrivateKey, pub *ecdsa.PublicKey) (*AuthDataQ, error) {
```
and
```go
func NewEC(n, k int) (*ECSpec, error) {
```
and
```go
func NewGQSortNoVis(rows, cols int) QuorumSpec {
```
I'm not sure how to work around these limitations for the second alternative without supplying a new `qspec`. Any ideas anyone?

**Comment by s111** [comment]
How about:
```go
func (m *Manager) NewConfiguration(...nodes, qsf func(n int, old QuorumSpec) (QuorumSpec, error)) (*Configuration, error) {
...
c.qspec = qsf(len(nodes), nil)
...
return c
}
```
Can a new quorum spec be generated given the old spec and the new number of nodes? That is, you could always cast QuorumSpec to the correct type and inspect the details. In the case that you really need to supply new information, i.e., new certificates, you could just call the regular `Manager.NewConfiguration` and provide the new quorum spec.

Though, it might just be easier to pass a new quorum spec, as this is starting to become a little too complicated...

**Comment by tormoder** [comment]
I think the best option is to pass the new quorum spec as an (interface) argument.

The user can create the new quorum spec implementation manually or using a factory before passing it to add method (just as when using `Manager.NewConfiguration`).

As you say, a factory function implementation passed as a parameter would involve a type assertion inside the factory, and we can't use parameters such as  `n`, they vary for each use case.
