### ISSUE TITLE
reorganizing: move examples to separate repos

### ISSUE THREAD

**Issue by meling** [relab/gorums#3]
We should keep examples (such as byzq and gridq and gbench clients etc) in separate repos, or in one common repo with many examples. Reason: people often want to look at examples of how to use gorums in their own project, and the examples in byzq and friends may not be representative for how to use it from another project. At least it turns out that they run into issues with dependencies and stuff that we don't experience because of the current organization.

**Comment by meling** [comment]
When we move the examples to separate repos, we should provide links to those repos from the main readme page.

**Comment by meling** [comment]
I started to move `byzq` out of the gorums repo. Discovered a few issues related to vendoring that I'm not sure how best to handle. I think the best approach is to move also `gridq` to its own repo. 

Then I propose to also move the `gbench` package and `cmd/gbenchclient` to a new `gbench` repo. This repo can depend on `gorums`, `byzq`, `gridq`, and whatever other gbench clients we want to support. 

Further, I propose that the `RequestFactory` implementations reside in a `gbench` package in their respective repos, e.g. as in `byzq/gbench/byzq_requester.go`.

I'm not sure if `gbench/common.go` is needed in each of the `gbench` packages; probably it is only needed by the `cmd/gbenchclient`.

Let me know if you agree with this organization, and feel free to take care of moving `gridq` and `gbench` stuff.

My only concern is how to handle vendoring. I think that all protocols that depend on `gorums` should use the same vendored dependencies as gorums. But I'm not sure how to set up the subrepos to inherit `gorums'` dependencies, or if there is a better way. I prefer to not have a separate vendor folder in each of the subrepos. Could you take a look at this issue and explain to me how best to deal with this @tormoder ??

I see that `rkv` does have a vendor folder, while `raft` does not. How is that working out @s111 ?

**Comment by s111** [comment]
`raft` does not have a vendor folder as it is a library, i.e., it doesn't compile into a binary by itself. `rkv` on the other hand compiles to a binary and therefore needs a vendor folder to pin the specific libraries that it depends on. This allow the binary (`rkv`) to decide which version of a library is used, and not the library itself. I think my approach works good for my use case, I do get a little trouble by working on both `rkv` and `raft` at the same time (as I need to update `rkv`'s dependencies each time I update `raft`), but for a user of the `raft` library, I think this approach is preferable.

As `gorums` is not a library and only generates code to be included in your own project, I think the `gorums` repo should be vendored. However, it might be beneficial to move the "standalone" projects that uses `gorums` out of the repository, as I think it's easier for a beginner to sort out what is relevant to `gorums` and what's not.

**Comment by tormoder** [comment]
Gorums outputs code (a library) for projects to use in their applications. The code generated by gorums has external dependencies, but it is the application (final binary) that uses our generated code that decides what version of theses dependencies to vendor. We can't control that.

As @s111 says, every repository with binaries has to vendor their own dependencies.

As an example, `byzq` must vendor to lock the external dependencies for the two binaries in `cmd`.
That is mainly grpc, net/trace, protobuf dependencies.
There are no gorums dependencies to vendor (except the `github.com/relab/gorums` package, but that is #23). The generated code (`pb.go`) is "manually" vendored by copying it to the project.

If `gridq` and `byzq` are separate repositories, we will have to handle vendoring separately for both of them. If they reside in an `example` repo, they can share the vendored dependencies.

I will have to look at the `gbench` stuff, I don't remember the details.

**Comment by meling** [comment]
I've moved the remaining examples and gbench stuff out of the main repo and into separate repos for each example and a special one for `gbench` things. If @tormoder could take a look at the new structure and confirm that it is ok, perhaps we can close this issue. 

Note that I currently only vendor in the `gbench` repo, but since the other examples (byqz and gridq) also contains binaries, they maybe should be vendored too. 

Also note that, it seems that it is possible to do `dep prune` to avoid so many files in the vendor folder. Not sure if this has any adverse effects... but it would be strange if so... I didn't notice any problems.

**Comment by meling** [comment]
Closing this issue, since the move/reorg has been completed a long time ago, and I've just written up a note about vendoring with Gorums, summarizing some of the explanations above.
