### ISSUE TITLE
Allow adding new nodes on the fly

### ISSUE THREAD

**Issue by s111** [relab/gorums#30]
Is there any reasons that the list of nodes need to be specified up front? As we are always creating a "new configuration", I don't see a problem with adding nodes at runtime to a new configuration.

For starters:
- Remove the `nodeAddrs` argument from `NewManager`.
- `Manager.NewConfiguration` creates connections to non-existent nodes on the fly, adding them to the manager for re-use.

**Comment by meling** [comment]
Issues #27, #28, #29, #30 and to some degree #17 are related. I've proposed a project related to these topics for the master students; it wasn't picked up by anyone so far, but I expect someone may pick it up for a master thesis.

**Comment by tormoder** [comment]
The was previously some quirks related to this, but now I think it is pretty straightforward.

**Comment by meling** [comment]
New nodes can now be created with
```go
	n, err := gorums.NewNodeWithID("localhost:9091", 0)
	n, err := gorums.NewNode("localhost:9091")
```
And nodes can be added to the manager, which will also establish the connection via:
```go
	err = mgr.AddNode(n)
```
After this, a new configuration can be created that uses the new nodes.

This isn't exactly what was proposed in this issue. I do think the idea to drop passing a list or map of nodes as input to the manager is a good one. We should pass nodes as input to at configuration creation instead.
