### ISSUE TITLE
Manual changes to vendor/ breaks 'dep ensure (-update)'

### ISSUE THREAD

**Issue by tormoder** [relab/gorums#39]
We should not do manual changes to the `vendor/` directory.

I currently can't run `dep ensure` / `dep ensure -update` / `dep ensure -update [grpc-pkg-path]` without introducing changes that will break the build/tests.

I wanted to update gRPC to a newer version, but updating the current dependencies will overwrite our current patch to `gogo/protofbuf`.

A temporary solution could be to have the patch on it's own branch of our already existing fork of `gogo/protobuf` and vendor it, but that will lead to import path problems since `dep` doesn't support aliasing (`glide` does I think).

**Comment by meling** [comment]
Right. I'm hopeful that the change will be supported in an updated version of `gogo`, but I've not had time to follow up on that issue in the last week or so. See Issue [341](https://github.com/gogo/protobuf/pull/341) for the current status. Perhaps you could direct `dep` to use [my fork](https://github.com/meling/protobuf) until the PR has been finally accepted??

**Comment by tormoder** [comment]
Yes, will do.

I thought `dep` didn't support forks, but it appears it does (using the `source` option).
