### ISSUE TITLE
Gorums returns quorum call error: incomplete call (errors: 4, replies: 0) hiding underlying error

### ISSUE THREAD

**Issue by meling** [relab/gorums#41]
I get this error:
```
error reading: quorum call error: incomplete call (errors: 4, replies: 0)
```
But I don't get the underlying error causing the problem. 
@tormoder  What to do about it?  Shouldn't the error be propagated?

**Comment by tormoder** [comment]
We don't store the underlying errors now, but we can store and expose them.
We can store them as a slice of the existing `GRPCError` type, and also then remove `errCount` and just use `len`.

Note that you would probarly need to cast the error (interface) to `QuorumCallError` to access the slice of errors. I would prefer to keep `Error()` string as it is, and not be a very long (multi-line string).

**Comment by tormoder** [comment]
I should be possible to now do something like:

```go
qcErr, ok := err.(qc.QuorumCallError)
if ok {
    // Access qcErr.Errors
}
```
